# Generated by Django 4.0.4 on 2022-04-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateField(blank=True, verbose_name='Due(mm/dd/yyyy)'),
        ),
    ]
